ts3server:
  relayPort: 9987
  remoteAddr: 127.0.0.1
  remotePort: 9987
ts3FileTransfer:
  relayPort: 30033
  remoteAddr: 127.0.0.1
  remotePort: 30033
ts3ServerQuery:
  relayPort: 10011
  remoteAddr: 127.0.0.1
  remotePort: 10011